id: A3E2CFAD0
title: Toh_155-The_Question_of_the_Naga_King-v1
type: translation
pechas:
- IF48CF787
- IAE991D1E
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-18T06:19:40.66Z'
  creationid: dirk
  eft-text-id: UT22084-058-002
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_155-The_Question_of_the_Naga_King-v1
alignment_to_base:
  IF48CF787/7EE7: 36CE
  IAE991D1E/4035: 36CE
